base_images:
  base:
    name: "4.9"
    namespace: ocp
    tag: base
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  ocp_builder_golang-1.13:
    name: builder
    namespace: ocp
    tag: golang-1.13
  ocp_builder_rhel-8-golang-1.15-openshift-4.6:
    name: builder
    namespace: ocp
    tag: rhel-8-golang-1.15-openshift-4.6
  ocp_builder_rhel-8-golang-1.15-openshift-4.7:
    name: builder
    namespace: ocp
    tag: rhel-8-golang-1.15-openshift-4.7
  ocp_builder_rhel-8-golang-1.15-openshift-4.8:
    name: builder
    namespace: ocp
    tag: rhel-8-golang-1.15-openshift-4.8
  ocp_builder_rhel-8-golang-1.16-openshift-4.8:
    name: builder
    namespace: ocp
    tag: rhel-8-golang-1.16-openshift-4.8
  ocp_builder_rhel-8-golang-openshift-4.6:
    name: builder
    namespace: ocp
    tag: rhel-8-golang-openshift-4.6
  openshift_release_golang-1.13:
    name: builder
    namespace: ocp
    tag: rhel-8-golang-openshift-4.6
build_root:
  from_repository: true
images:
- dockerfile_path: images/router/base/Dockerfile.rhel
  from: base
  inputs:
    ocp_builder_rhel-8-golang-1.16-openshift-4.8:
      as:
      - registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.16-openshift-4.8
  optional: true
  to: haproxy-router-base
- dockerfile_path: images/router/haproxy/Dockerfile.rhel8
  from: haproxy-router-base
  to: haproxy-router
- dockerfile_path: images/router/f5/Dockerfile
  from: haproxy-router-base
  to: f5-router
promotion:
  name: "4.9"
  namespace: ocp
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tag_specification:
  name: "4.9"
  namespace: ocp
tests:
- as: verify
  commands: make verify
  container:
    from: src
- as: unit
  commands: go test -race ./...
  container:
    from: src
- as: e2e-agnostic
  steps:
    cluster_profile: azure4
    workflow: openshift-e2e-azure
- as: e2e-metal-ipi-ovn-ipv6
  steps:
    cluster_profile: packet
    workflow: baremetalds-e2e-ovn-ipv6
- as: e2e-metal-ipi-ovn-dualstack
  steps:
    cluster_profile: packet
    workflow: baremetalds-e2e-ovn-dualstack
- as: e2e-aws-serial
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws-serial
- as: e2e-metal-ipi-ovn-router
  steps:
    cluster_profile: packet
    workflow: baremetalds-e2e-ovn-router
- as: e2e-upgrade
  steps:
    cluster_profile: azure4
    workflow: openshift-upgrade-azure
zz_generated_metadata:
  branch: master
  org: openshift
  repo: router
